language: objective-c
osx_image: xcode9.4

script:
  - xcodebuild -project Erbium.xcodeproj -scheme Erbium -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
